# utils/constants.py

DEFAULT_IMAGE_SAVE_PATH = "assets/images/generated_image.png"
DEFAULT_GIF_OUTPUT_PATH = "assets/images/generated_gif.gif"
PLACEHOLDER_IMAGE_PATH = "assets/images/placeholder.png"



   # test for mapping weather to traits (in case of emergency)
WEATHER_TO_TRAITS = {
    "Clear": {"alignment": "Lawful Good", "race": "Elf"},
    "Clouds": {"alignment": "Neutral", "race": "Human"},
    "Rain": {"alignment": "Chaotic Neutral", "race": "Tiefling"},
    "Thunderstorm": {"alignment": "Chaotic Evil", "race": "Half-Orc"},
    "Snow": {"alignment": "Lawful Neutral", "race": "Dwarf"},
}

    # this race dictionary is linked / generated by Chat GPT
WEATHER_CODE_TO_RACE = {
    200: 'Half-Orc',
    201: 'Kenku',
    202: 'Gnome',
    210: 'Locathah',
    211: 'Shadar-kai',
    212: 'Autognome',
    221: 'Triton',
    230: 'Warforged',
    231: 'Owlin',
    232: 'Half-Elf',
    300: 'Kobold',
    301: 'Dwarf',
    302: 'Hadozee',
    310: 'Loxodon',
    311: 'Tortle',
    312: 'Harengon',
    313: 'Verdan',
    314: 'Hexblood',
    321: 'Tiefling',
    500: 'Grung',
    501: 'Dhampir',
    502: 'Githzerai',
    503: 'Changeling',
    504: 'Yuan-Ti Pureblood',
    511: 'Halfling',
    520: 'Leonin',
    521: 'Aarakocra',
    522: 'Thri-kreen',
    531: 'Satyr',
    600: 'Goblin',
    601: 'Hobgoblin',
    602: 'Kalashtar',
    611: 'Eladrin',
    612: 'Dragonborn',
    613: 'Shifter',
    615: 'Sea Elf',
    616: 'Elf',
    620: 'Vedalken',
    621: 'Genasi',
    622: 'Orc',
    701: 'Bugbear',
    711: 'Fairy',
    721: 'Plasmoid',
    731: 'Reborn',
    741: 'Firbolg',
    751: 'Lizardfolk',
    761: 'Astral Elf',
    762: 'Tabaxi',
    771: 'Centaur',
    781: 'Githyanki',
    800: 'Goliath',
    801: 'Minotaur',
    802: 'Simic Hybrid',
    803: 'Human',
    804: 'Aasimar'
}

    # I toggled the above classes with different AI tools until I got a randomized dict I liked... 
WEATHER_MAIN_TO_CLASSES = {
    "Thunderstorm": ["Barbarian", "Sorcerer", "Warlock"],
    "Drizzle": ["Druid", "Cleric", "Ranger"],
    "Rain": ["Rogue", "Monk", "Druid"],
    "Snow": ["Wizard", "Cleric", "Paladin"],
    "Clear": ["Fighter", "Paladin", "Bard"],
    "Clouds": ["Wizard", "Artificer", "Bard"],
    "Mist": ["Monk", "Warlock", "Cleric"],
    "Smoke": ["Rogue", "Artificer", "Druid"],
    "Haze": ["Bard", "Warlock", "Ranger"],
    "Dust": ["Fighter", "Ranger", "Barbarian"],
    "Fog": ["Cleric", "Monk", "Warlock"],
    "Sand": ["Ranger", "Druid", "Barbarian"],
    "Ash": ["Sorcerer", "Warlock", "Wizard"],
    "Squall": ["Fighter", "Barbarian", "Rogue"],
    "Tornado": ["Barbarian", "Sorcerer", "Monk"]
}

    # these don't change so I had Chat GPT generate them
ALIGNMENTS = [
    "Lawful Good", "Neutral Good", "Chaotic Good",
    "Lawful Neutral", "True Neutral", "Chaotic Neutral",
    "Lawful Evil", "Neutral Evil", "Chaotic Evil"
]

    # I wanted to stick to core classses without fluff
CLASSES = [
    "Artificer", "Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", 
    "Paladin", "Ranger", "Rogue", "sorcerer", "Warlock", "Wizard",
]

    # this is my race list / link to weather codes to make dict
    # actually, RACES is used when weather code is missing or unrecognized
    # but I'm keeping it around in case it becomes a worthy option 
RACES = [
    "Aasimar", "Aarakocra", "Bugbear", "Centaur", "Changeling", "Dark Elf", "High Elf", "Wood Elf", "Elf",
    "Fairy", "Firbolg", "Duergar", "Hill Dwarf", "Mountain Dwarf", "Black Dragonborn", "Copper Dragonborn", 
    "Brass Dragonborn", "Gold Dragonborn", "Bronze Dragonborn", "Blue Dragonborn", "Green Dragonborn", 
    "Genasi", "Red Dragonborn", "Silver Dragonborn", "White Dragonborn", "Dwarf", "Air Genasi", "Earth Genasi", 
    "Fire Genasi", "Water Genasi", "Gnome", "Goliath", "Half-Elf", "Half-Orc", "Halfling", "Harengon", 
    "Hobgoblin", "Human", "Leonin", "Lizardfolk", "Loxodon", "Minotaur", "Merfolk", "Orc", "Owlin", 
    "Pixie", "Satyr", "Shifter", "Tiefling", "Triton", "Tabaxi", "Vedalken", "Verdan", "Warforged", "Yuan-Ti", 
] 